[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# Keep strong linting for .py files
select = ["E", "F", "I", "B", "UP", "SIM"]
ignore = ["E203"]

# Ignore some rules in notebooks
per-file-ignores = { "*.ipynb" = ["E501", "B018", "F811"] }
